// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUsers(ctx context.Context) error
	DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error
	GetFeedByUrl(ctx context.Context, url string) (Feed, error)
	GetFeedFollowForUserAndFeed(ctx context.Context, arg GetFeedFollowForUserAndFeedParams) (GetFeedFollowForUserAndFeedRow, error)
	GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserRow, error)
	GetFeedsWithUserName(ctx context.Context) ([]GetFeedsWithUserNameRow, error)
	GetNextFeedToFetch(ctx context.Context) (Feed, error)
	GetUser(ctx context.Context, name string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error
}

var _ Querier = (*Queries)(nil)
